from ctypes import c_int

WEBKIT_LOAD_PROVISIONAL = c_int(0)
WEBKIT_LOAD_COMMITTED = c_int(1)
WEBKIT_LOAD_FINISHED = c_int(2)
WEBKIT_LOAD_FIRST_VISUALLY_NON_EMPTY_LAYOUT = c_int(3)
WEBKIT_LOAD_FAILED = c_int(4)
